# Generated by Django 4.2.6 on 2025-04-06 10:12
import logging
import environ
from django.db import migrations
from storages.models import Storages
from storages.functions import mk_storage

logger = logging.getLogger(__name__)
logging.basicConfig()

def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    env = environ.Env()
    USERNAME = env.str("ADMIN_USERNAME")
    PASSWORD = env.str("ADMIN_PASSWORD")
    EMAIL = env.str("ADMIN_EMAIL") 

    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
           username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()
        storage_user_new = Storages.objects.create(user_id = admin.id, count_files = 0, total_files_size = 0)
        mk_storage(storage_user_new.id)
    else:
        logger.info("Superuser already created!")

class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
