# Generated by Django 4.2.6 on 2025-04-13 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_files', models.IntegerField()),
                ('total_files_size', models.BigIntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_origin', models.CharField(max_length=255)),
                ('name_storage', models.UUIDField(editable=False)),
                ('size', models.PositiveBigIntegerField(editable=False)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('date_load', models.DateTimeField(auto_now_add=True)),
                ('date_download', models.DateTimeField(blank=True, null=True)),
                ('public_url', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.storages')),
            ],
        ),
    ]
